# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            Partially Attended
tagline:          'an infrequently updated blog'
description:      "Ian Mulvany's blog"
url:              http://partiallyattended.com
baseurl:          /

author:
  name:           'Ian Mulvany'
  url:            http://mulvany.net

paginate:         10

# Custom vars


github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]
